language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kgurbey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kgurbey/docker-react npm run test